name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  type-check:
    name: TypeScript checks
    needs: [setup-node]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          cache: 'yarn'
          node-version-file: '.nvmrc'
      - name: Install dependencies
        run: yarn
      - name: Run Typescript checks
        run: yarn type-check

  unit-tests:
    name: Unit tests
    needs: [type-check]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          cache: 'yarn'
          node-version-file: '.nvmrc'
      - name: Install dependencies
        run: yarn
      - name: Run unit tests
        run: yarn test:unit

    integration-tests:
      name: Integration tests
      needs: [type-check]
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Setup node
          uses: actions/setup-node@v2
          with:
            cache: 'yarn'
            node-version-file: '.nvmrc'
        - name: Install dependencies
          run: yarn
        - name: Run integration tests
          run: yarn test:integration

    upload coverage:
      name: Upload coverage
      needs: [unit-tests, integration-tests]
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Setup node
          uses: actions/setup-node@v2
          with:
            cache: 'yarn'
            node-version-file: '.nvmrc'
        - name: Install dependencies
          run: yarn
        - name: Run tests and get coverage
          run: yarn test:coverage
        - name: Upload coverage to Codecov
          uses: codecov/codecov-action@v2
          with:
            token: ${{ secrets.CODECOV_TOKEN }}
            fail_ci_if_error: true
            files: ./coverage/coverage-final.json
            flags: unittests
            name: codecov-pampa.place
            verbose: true
