name: CI Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  setup-node:
    name: Setup node
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Read .nvmrc
        run: echo NVMRC=`cat .nvmrc` >> $GITHUB_ENV
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          cache: 'yarn'
          node-version: ${{ env.NVMRC }}
      - name: Install dependencies
        run: yarn

  type-check:
    name: Run type checks
    needs: [setup-node]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Install dependencies
        run: yarn
      - name: Run Typescript checks
        run: yarn type-check

  tests:
    name: Run tests
    needs: [type-check]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Install dependencies
        run: yarn
      - name: Run tests and get coverage
        run: yarn test:coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          files: ./coverage/coverage-final.json
          flags: unittests
          name: codecov-pampa.place
          verbose: true
