name: Type Checks

on: pull_request

jobs:
  type-check:
    name: Typescript
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: yarn

      - name: Run Typescript checks
        run: yarn type-check
